Action/SmartSuite
Bit-Apps-Pro/bit-integrations pull request #78
Opened 2024-12-25 11:25 UTC by rahatyeasinemon

2024-12-28 04:40 UTC, RishadAlam requested changes

2024-12-28 09:19 UTC, rahatyeasinemon commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteCommonFunc.js
> +    delete confTmp?.selectedTable
It is used to refresh the select table drop-down menu, after clicking refresh table button

2024-12-28 09:24 UTC, rahatyeasinemon commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteCommonFunc.js
> +    delete confTmp?.selectedSolution
It is used to refresh the select solution drop-down menu, after clicking refresh solution button

2024-12-29 06:31 UTC, rahatyeasinemon commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteIntegLayout.jsx
> +  }
This is used to hide the field-map section at the Record action, when no table is selected.

2024-12-29 09:03 UTC, RishadAlam commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteCommonFunc.js
> +    delete confTmp?.selectedTable
Then why you removed the selectedTable after clicking refresh table button?

2024-12-29 09:05 UTC, RishadAlam commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteCommonFunc.js
> +    delete confTmp?.selectedSolution
Then why you removed the selectedSolution after clicking refresh table button?

2024-12-29 09:22 UTC, RishadAlam commented on frontend-dev/src/components/AllIntegrations/SmartSuite/IntegrationHelpers.jsx
> +  const newConf = { ...conftTmp }
Provide an explanation of how to use handleCustomValue and handleCustomField, and specify which file contains these functions.

2024-12-29 10:54 UTC, RishadAlam commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteIntegLayout.jsx
> +  }
remove handleCustomFieldForRecord function

2024-12-29 10:55 UTC, RishadAlam commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteIntegLayout.jsx
> +      {handleCustomFieldForRecord(smartSuiteConf.actionName, smartSuiteConf.selectedTable) &&
use smartSuiteConf.actionName === 'record' && smartSuiteConf.selectedTable !== ''

2024-12-29 11:16 UTC, RishadAlam commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteIntegLayout.jsx
> +          delete draftConf['priority']
reset smartSuiteFields & hendle getAllSolutions function in separete condition

2024-12-29 11:26 UTC, RishadAlam commented on includes/Actions/SmartSuite/RecordApiHelper.php
> +        }
check action name record for creating record & for default apiResponse use null or false something

2024-12-29 11:29 UTC, RishadAlam commented on includes/Actions/SmartSuite/RecordApiHelper.php
> +        return handleFilterResponse($response);
send integrationDetails instead of sending integrationDetails  properties

2024-12-29 11:51 UTC, RishadAlam requested changes
Make changes to the comment below

2025-01-12 06:04 UTC, rahatyeasinemon commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteCommonFunc.js
> +    delete confTmp?.selectedTable
![Screenshot 2025-01-12 120033](https://github.com/user-attachments/assets/e3a19d05-bc5a-41bf-97a3-a3d5bbaf9167)

The reason is, after clicking refresh table button, our selectedTable variable is needed to empty, to show the UI effect attached to the screen-shot.

No table will not be selected by default after clicking the refresh table button.

2025-01-12 06:06 UTC, rahatyeasinemon commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteCommonFunc.js
> +    delete confTmp?.selectedSolution
This is the same reason, why do we need to delete the selectedTable vaiable, after clicking the refresh table button.

2025-01-12 06:41 UTC, rahatyeasinemon commented on frontend-dev/src/components/AllIntegrations/SmartSuite/SmartSuiteIntegLayout.jsx
> +  }
removed

2025-01-12 06:42 UTC, rahatyeasinemon commented on frontend-dev/src/components/AllIntegrations/SmartSuite/IntegrationHelpers.jsx
> +  const newConf = { ...conftTmp }
removed

2025-01-12 09:51 UTC, RishadAlam requested changes

2025-01-12 09:51 UTC, RishadAlam commented on frontend-dev/src/components/AllIntegrations/MondayCRM/CustomField.jsx
> +  index,
Removed this component

2025-01-12 10:09 UTC, RishadAlam approved these changes

2025-01-14 06:08 UTC, shuvomohajan approved these changes

2025-01-14 06:25 UTC, shuvomohajan approved these changes

2025-01-16 05:03 UTC, merged